python trainer/train_trans_generator.py \
--order C-M \
--dataset_name proteins \
--max_epochs 5000 \
--check_sample_every_n_epoch 200 \
--replicate 0 \
--max_len 1575 \
--wandb_on online \
--string_type adj_list_diff_ni_rel \
--lr 0.001 \
--batch_size 4 \
--num_samples 60 \
--sample_batch_size 5 \
--pe no