python trainer/train_trans_generator.py \
--order C-M \
--dataset_name Caveman \
--max_epochs 500 \
--check_sample_every_n_epoch 20 \
--replicate 0 \
--max_len 104 \
--num_samples 1000 \
--wandb_on online \
--string_type bfs \
--lr 0.0005 \
;
python trainer/train_trans_generator.py \
--order C-M \
--dataset_name Caveman \
--max_epochs 500 \
--check_sample_every_n_epoch 20 \
--replicate 0 \
--max_len 104 \
--num_samples 1000 \
--wandb_on online \
--string_type bfs \
--lr 0.0002 \
;
python trainer/train_trans_generator.py \
--order C-M \
--dataset_name Caveman \
--max_epochs 500 \
--check_sample_every_n_epoch 20 \
--replicate 0 \
--max_len 104 \
--num_samples 1000 \
--wandb_on online \
--string_type bfs \
--lr 0.0001 \