python trainer/train_trans_generator.py \
--order C-M \
--dataset_name GDSS_grid \
--max_epochs 500 \
--check_sample_every_n_epoch 20 \
--replicate 0 \
--max_len 5436 \
--wandb_on online \
--string_type group \
--lr 0.0005 \
--batch_size 32 \
--sample_batch_size 50 \
--num_samples 500 \
;
python trainer/train_trans_generator.py \
--order C-M \
--dataset_name GDSS_grid \
--max_epochs 500 \
--check_sample_every_n_epoch 20 \
--replicate 0 \
--max_len 5436 \
--wandb_on online \
--string_type group \
--lr 0.0001 \
--batch_size 32 \
--sample_batch_size 50 \
--num_samples 500 \