python trainer/train_trans_generator_feature_list.py \
--order C-M \
--dataset_name qm9 \
--max_epochs 1000 \
--check_sample_every_n_epoch 100 \
--replicate 0 \
--max_len 53 \
--wandb_on online \
--string_type adj_list_diff_ni \
--lr 0.0005 \
--batch_size 1024 \
--num_samples 10000